"""create_changed_ticket_modell

Revision ID: 85f8052747a1
Revises: 62bdb2550254
Create Date: 2026-09-25 17:38:55.944109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f8052747a1'
down_revision: Union[str, Sequence[str], None] = '62bdb2550254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tickets', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='unique')
    op.drop_column('tickets', 'idempotency_key')
    # ### end Alembic commands ###
