"""add status_changed_at

Revision ID: 987b89329160
Revises: fc9b68ac8710
Create Date: 2026-08-27 08:03:32.115770

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '987b89329160'
down_revision: str | Sequence[str] | None = 'fc9b68ac8710'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'status_changed_at')
    # ### end Alembic commands ###
