"""create_ticket_model

Revision ID: f3ffd8b8c8e4
Revises: 98213dca24f5
Create Date: 2026-09-25 07:45:43.638495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ffd8b8c8e4'
down_revision: Union[str, Sequence[str], None] = '98213dca24f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('sync_state')
    op.drop_table('places')
    # ### end Alembic commands ###
